### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by nbittmann** [michaelarnauts/cec-mqtt-bridge#1]
Hi there,

Great little tool and exactly what I was looking for however I cannot get the tool to send the status to MQTT on the terminal it says device status changed to on but subsrcbing on media/cec# gives me nothing at all?

Any ideas?

Initialising MQTT...
Initialising CEC...
Broadcast (F): osd name set to 'Broadcast'
InitHostCEC - vchiq_initialise succeeded
InitHostCEC - vchi_initialise succeeded
InitHostCEC - vchi_connect succeeded
logical address changed to Free use (e)
Open - vc_cec initialised
connection opened
<< Broadcast (F) -> TV (0): POLL
initiator 'Broadcast' is not supported by the CEC adapter. using 'Free use' instead
<< e0
Starting main loop...
Refreshing....
processor thread started
initiator 'Broadcast' is not supported by the CEC adapter. using 'Free use' instead
<< e0
>> POLL not sent
TV (0): device status changed into 'not present'
registering new CEC client - v3.0.1
detecting logical address for type 'recording device'
trying logical address 'Recorder 1'
<< Recorder 1 (1) -> Recorder 1 (1): POLL
<< 11
<< 11
>> POLL not sent
using logical address 'Recorder 1'
Recorder 1 (1): device status changed into 'handled by libCEC'
Recorder 1 (1): power status changed from 'unknown' to 'on'
Recorder 1 (1): vendor = Pulse Eight (001582)
Recorder 1 (1): CEC version 1.4
AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
logical address changed to Recorder 1 (1)
Recorder 1 (1): osd name set to 'cec-ir-mqtt'
Recorder 1 (1): menu language set to 'eng'
GetPhysicalAddress - physical address = 2400
AutodetectPhysicalAddress - autodetected physical address '2400'
Recorder 1 (1): physical address changed from ffff to 2400
<< Recorder 1 (1) -> broadcast (F): physical adddress 2400
<< 1f:84:24:00:01
CEC client registered: libCEC version = 3.0.1, client version = 3.0.1, firmware version = 1, logical address(es) = Recorder 1 (1) , physical address: 2.4.0.0,  compiled on Fri Jul  3 19:20:43 UTC 2015 by pbuilder@mgorven-pc.thefacebook.com on Linux 3.16.0-41-generic (armv7l), features: P8_USB, P8_detect, 'RPi'
<< Recorder 1 (1) -> TV (0): OSD name 'cec-ir-mqtt'
<< Recorder 1 (1) -> TV (0): POLL
<< 10
<< 10
>> POLL not sent
not sending command 'set osd name': destination device 'TV' marked as not present
<< requesting power status of 'TV' (0)
<< Recorder 1 (1) -> TV (0): POLL
<< 10
<< 10
>> POLL not sent
not sending command 'give device power status': destination device 'TV' marked as not present
<< 11:8f
not sending data to myself!

Config:

`;
; MQTT broker configuration
;
[mqtt]
; Hostname of mqtt broker (required)
broker=192.168.20.10

; Port to connect to (default=1883)
port=1883

; Username and password
user=REDACTED
password=REDACTED

; MQTT prefix to use
prefix=media

;
; HDMI-CEC configuration
;
[cec]
; Enable CEC
enabled=1

; ID of CEC controller
id=1

; Port where the CEC-device is connected
port=RPI

; Devices to query (comma seperated, defaults to all devices)
devices=1

;
; LIRC configuration
;
[ir]
; Enable LIRC
enabled=0
`

**Comment by michaelarnauts** [comment]
Is the device you want to monitor really `1` (Recorder 1)? Do you get responses when you uncomment `devices=1` so it queries all devices?
