### ISSUE TITLE
"No module named 'cec'" on latest OSMC

### ISSUE THREAD

**Issue by sunnythaper** [michaelarnauts/cec-mqtt-bridge#17]
After following all the instructions related to CEC (including the "install libcec" step) on [your guide](https://github.com/michaelarnauts/cec-mqtt-bridge/wiki/Installation-instructions), I am getting the following error when trying to run bridge.py:

```shell
osmc@osmc:/opt/cec-mqtt-bridge$ python3 bridge.py
Initialising CEC...
ERROR: Could not initialise CEC: No module named 'cec'
```

On this machine (Raspberry Pi) I can run cec-client commands just fine to turn on/off the connected devices (just a TV in my case). It also shows up on my Samsung as any Anynet+ device and can be controlled by my stock TV remote. 

Any ideas? I love the project concept and would absolutely love to get this going!

**Comment by sunnythaper** [comment]
A little further digging, I decided to compile libcec directly using your instructions once again in the wiki. This time I am getting a new error:

```shell
osmc@osmc:/opt/cec-mqtt-bridge$ python3 bridge.py
Initialising CEC...
ERROR: Could not initialise CEC: /usr/local/lib/python3.5/dist-packages/_cec.so: undefined symbol: _ZN11StringUtils6FormatB5cxx11EPKcz
```

**Comment by mjcumming** [comment]
I am seeing the same error per your second post.

**Comment by thecrane** [comment]
I get the same error as your first message.  Any joy in getting this solved?

**Comment by thecrane** [comment]
And then again, same error as per your second post.  :-(

**Comment by sunnythaper** [comment]
@thecrane I personally haven't figured it out yet :/

**Comment by michaelarnauts** [comment]
Sorry all, I'm running this on a raspberry pi with raspbian. I also have a Vero4K+ box with OSMC, but I had no luck in getting it to run on it since it conflicts with the CEC integration of Kodi itself.

**Comment by thecrane** [comment]
Ah.  Thanks @michaelarnauts - that's actually what I suspected, but was hoping wasn't the case.

It would be brilliant if the Kodi CEC integration would allow the recording of CEC events - or even the logging of them.  Then we could watch the log and publish the events for others that are interested in them on the network.

**Comment by michaelarnauts** [comment]
I made progress with CEC of running it together with Kodi.

I've added instructions for compiling on a Vero4K+ on the wiki [here](https://github.com/michaelarnauts/cec-mqtt-bridge/wiki/Compiling-libcec#osmc-vero4k). I'm not using the rpi anymore to run OSMC, so I can't test the rpi instructions, but they should be mostly the same...

It's important that the `cmake`-command of libcec gives this output.
```
...
-- AOCEC support:                          yes
-- Python support:                         version 3.5.3 (3.5)
```

**Comment by thecrane** [comment]
> I made progress with CEC of running it together with Kodi.
> 
> I've added instructions for compiling on a Vero4K+ on the wiki [here](https://github.com/michaelarnauts/cec-mqtt-bridge/wiki/Compiling-libcec#osmc-vero4k). I'm not using the rpi anymore to run OSMC, so I can't test the rpi instructions, but they should be mostly the same...
> 
> It's important that the `cmake`-command of libcec gives this output.
> 
> ```
> ...
> -- AOCEC support:                          yes
> -- Python support:                         version 3.5.3 (3.5)
> ```

Thanks @michaelarnauts - I've tried this, but when I run bridge.py it still gives the error: 
`ERROR: Could not initialise CEC: /usr/local/lib/python3.5/dist-packages/_cec.so: undefined symbol: _ZN11StringUtils6FormatB5cxx11EPKcz
`

Am I doing something wrong re: running the bridge?

**Comment by michaelarnauts** [comment]
It seems I get some related results when Googling for b5cxx11, you might want to explore that.
