### ISSUE TITLE
Mute/Volume Issue

### ISSUE THREAD

**Issue by schmittx** [michaelarnauts/cec-mqtt-bridge#21]
I'm running on a RPi connected to my Sony TV. Power on/off commands and status reporting work fine, but mute commands/status and volume commands/status do not work (with TV internal speakers). Do these only work with an external amp connected?

**Comment by michaelarnauts** [comment]
All the volume-related commands are for the AVR. You can use the raw tx commands to send HDMI CEC commands to the right address to control your TV. Just construct the right command on the cec-matic website.
