### ISSUE TITLE
Can't "Activate Source" via MQTT (Using directly via cec-client works)

### ISSUE THREAD

**Issue by ned-kelly** [michaelarnauts/cec-mqtt-bridge#25]
As the title suggests - I'm having issues activating the 'source' video using the cec-mqtt bridge...

- When I run `echo 'tx 5f:82:32:00' | /usr/bin/cec-client -s` - I can broadcast to change the source on my AVR to `3.2.0.0` (and it works) 

- However when I try and run the same command via MQTT (so in this case i'm running `mosquitto_pub -h x.x.x.x -t homeassistant/cec/tx -m '5f:82:32:00'` the command is received fine, however nothing is executed...

To make matters more interesting, I can use the `prefix/cec/cmd` arguments (such as `mute/unmute` etc) -- So the issue appears only when running raw TX commands...

Anyone have any suggestions? I have a feeling this is a bug but I'm not sure what other information to provide...

Using latest build on github

**Comment by austinlg96** [comment]
I'm experiencing the same issue. I've got it running in a docker container right now. Have you had any progress?

**Comment by ned-kelly** [comment]
> I'm experiencing the same issue. I've got it running in a docker container right now. Have you had any progress?

Nope, for now just using `cec-client` and executing remotely via SSH - really hope that the author see's this issue as doing it via MQTT is a lot quicker than via SSH, as the CEC connection is always open, so commands are processed immediately when using `cec-mqtt`.

**Comment by ned-kelly** [comment]
@austinlg96 (and anyone else reading this in the future)... Finally figured it -- Basically, if the CEC adaptor is open whens starting by another device (say cec-client), or opened while cec-mqtt is running, then the service will fail _(In my case, I had Home Assistant manually running cec-client also every 5 minutes which was breaking my cec-mqtt)_...

Would be good to add some sort of error handling in here, and the ability to re-gain control of the CEC device if this happens...

**Comment by michaelarnauts** [comment]
@ned-kelly feel free to open a new issue for the auto reconnecting. I haven't looked at this code in a long time, so I'm not sure how it behaves on the initial connect, but I think I had something in there to reconnect when it got disconnected...
