### ISSUE TITLE
Default Config 

### ISSUE THREAD

**Issue by DomQuixote** [michaelarnauts/cec-mqtt-bridge#5]
I had several issues with the config: when I entered a different port it told me it could not compare str and int. I then decided to just change the config in the bridge.py file, which worked, but only after I  added "user":"" in the default dictionary, as it does not contain this.

It now works for me, but maybe have a look?

**Comment by michaelarnauts** [comment]
I always used the default port. When python reads the config.ini, it parsed the port as a string, while it should be a int. I've commited a fix for this.

The user seems to work fine however when configured from the config.ini. It's also possible to configure it trough ENV variables. This may come in handy when using the Dockerfile.

If you still have an issue with this, feel free to reopen.
