### ISSUE TITLE
Execute commands

### ISSUE THREAD

**Issue by 8666** [michaelarnauts/cec-mqtt-bridge#7]
I have done something like this long time before (CEC<-> Telnet) and it is time to move to MQTT. What I miss in your bridge is the ability to execute commands. There should be a topic where PI will subscribe to commands like 'click' and then execute 'xdotool click 1'. So clicking OK on the remote will send it to the home automation system and it will reply back to simulate Click. I use it to navigate web page and click buttons without a mouse

http://tuxradar.com/content/xdotool-script-your-mouse'

**Comment by michaelarnauts** [comment]
Hi! Thanks for the suggestion, but I consider that suggestion to be out of scope for this project. The purpose of this bridge is to run on a headless pi that's connected with your TV or AVR and control your equipment trough this bridge. You could setup a additional project that allows executing programs by listening to a topic based on this, it should not be that difficult.
