### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by schmittx** [michaelarnauts/cec-mqtt-bridge#9]
Any chance you can provide some basic instructions to install, setup, and run for an RPi running Raspbian?

**Comment by schmittx** [comment]
Can anyone help with some basic instructions to install?

**Comment by schmittx** [comment]
Yeah, I ended up getting it with enough hacking. I ended up using systemd service to keep it running in the background, but still have to figure out how to reference the config.ini file in that case.

**Comment by michaelarnauts** [comment]
Feel free to make a PR to improve the docs :)

**Comment by michaelarnauts** [comment]
You need to rename the `config.default.ini` to `config.ini` and modify the values. You probably need to specify the working directory in systemd so it can find the config file.

**Comment by schmittx** [comment]
Yep, that's exactly what I did. I finally got everything working pretty smoothly but I couldn't figure out how to install LibCEC from the directory in this repo, I just compiled by myself.
